export const RELEVANT_STYLE_PROPS = new Set([
    "display",
    "position",
    "top",
    "left",
    "right",
    "bottom",
    "width",
    "height",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "color",
    "background-color",
    "border",
    "border-radius",
    "font-size",
    "font-weight",
    "line-height",
    "opacity",
    "visibility",
    "z-index",
    "overflow",
    "flex-direction",
    "justify-content",
    "align-items",
]);

export const MAX_HTML_CHARS = 5000;
